# version : '3'

# the services part
services:
#mariadb
  mariadb:
    # image: mariadb:user
    container_name: mariadb
    build: ./requirements/mariadb
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    env_file :
      - .env
    networks :
      - inception
    restart: always
#nginx
  nginx:
    # image: nginx:user
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      timeout: 5s
      retries: 3
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
    restart: always
#wordpress
  wordpress:
    # image: wordpress:user
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/html/wordpress
    env_file :
      - .env
    networks:
      - inception
    restart: always

# the volumes part
volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/data/mariadb
      o : bind
      type : none

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/data/wordpress
      o : bind
      type : none

# the networks part
networks:
  inception:
    name: inception